CO453-WebApps/Controllers/MessagePostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CO453_WebApps.Data;
using CO453_WebApps.Models;

namespace CO453_WebApps.Controllers
{
    public class MessagePostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MessagePostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MessagePosts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Messages.ToListAsync());
        }

        // GET: PhotoPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var messagePost = await _context.Messages
                .Include(c => c.Comments)
                .FirstOrDefaultAsync(m => m.PostID == id);


            if (messagePost == null)
            {
                return NotFound();
            }

            return View(messagePost);
        }

        // GET: MessagePosts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MessagePosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Message,PostID,Username")] MessagePost messagePost)
        {
            if (ModelState.IsValid)
            {
                _context.Add(messagePost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(messagePost);
        }

        // GET: MessagePosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var messagePost = await _context.Messages.FindAsync(id);
            if (messagePost == null)
            {
                return NotFound();
            }
            return View(messagePost);
        }

        // POST: MessagePosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Message,PostID,Username")] MessagePost messagePost)
        {
            if (id != messagePost.PostID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(messagePost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessagePostExists(messagePost.PostID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(messagePost);
        }

        // GET: MessagePosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var messagePost = await _context.Messages
                .FirstOrDefaultAsync(m => m.PostID == id);
            if (messagePost == null)
            {
                return NotFound();
            }

            return View(messagePost);
        }

        // POST: MessagePosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var messagePost = await _context.Messages.FindAsync(id);
            _context.Messages.Remove(messagePost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Like(int id)
        {
            var messagePost = _context.Messages.Find(id);

            if (messagePost == null)
            {
                return NotFound();
            }
            messagePost.Like();
            try
            {
                _context.Update(messagePost);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MessagePostExists(messagePost.PostID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Details", new { id = id });
        }

        public ActionResult Unlike(int id)
        {
            var messagePost = _context.Messages.Find(id);

            if (messagePost == null)
            {
                return NotFound();
            }
            messagePost.Unlike();
            try
            {
                _context.Update(messagePost);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MessagePostExists(messagePost.PostID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Details", new { id = id });
        }

        private bool MessagePostExists(int id)
        {
            return _context.Messages.Any(e => e.PostID == id);
        }
    }
}

CO453-WebApps/Controllers/PhotoPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CO453_WebApps.Data;
using CO453_WebApps.Models;

namespace CO453_WebApps.Controllers
{
    public class PhotoPostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PhotoPostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PhotoPosts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Photos.ToListAsync());
        }

        // GET: PhotoPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photoPost = await _context.Photos
                .Include(c => c.Comments)
                .FirstOrDefaultAsync(m => m.PostID == id);


            if (photoPost == null)
            {
                return NotFound();
            }

            return View(photoPost);
        }

        // GET: PhotoPosts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PhotoPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Filename,Caption,PostID,Username")] PhotoPost photoPost)
        {
            if (ModelState.IsValid)
            {
                _context.Add(photoPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(photoPost);
        }

        // GET: PhotoPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photoPost = await _context.Photos.FindAsync(id);
            if (photoPost == null)
            {
                return NotFound();
            }
            return View(photoPost);
        }

        // POST: PhotoPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Filename,Caption,PostID,Username")] PhotoPost photoPost)
        {
            if (id != photoPost.PostID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(photoPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhotoPostExists(photoPost.PostID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(photoPost);
        }

        // GET: PhotoPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photoPost = await _context.Photos
                .FirstOrDefaultAsync(m => m.PostID == id);
            if (photoPost == null)
            {
                return NotFound();
            }

            return View(photoPost);
        }

        // POST: PhotoPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var photoPost = await _context.Photos.FindAsync(id);
            _context.Photos.Remove(photoPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Like(int id)
        {
            var photoPost = _context.Photos.Find(id);

            if (photoPost == null)
            {
                return NotFound();
            }
            photoPost.Like();
            try
            {
                _context.Update(photoPost);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PhotoPostExists(photoPost.PostID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Details", new { id = id });
        }

        public ActionResult Unlike(int id)
        {
            var photoPost = _context.Photos.Find(id);

            if (photoPost == null)
            {
                return NotFound();
            }
            photoPost.Unlike();
            try
            {
                _context.Update(photoPost);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PhotoPostExists(photoPost.PostID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Details", new { id = id });
        }

        private bool PhotoPostExists(int id)
        {
            return _context.Photos.Any(e => e.PostID == id);
        }
    }
}

CO453-WebApps/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CO453_WebApps.Data;
using CO453_WebApps.Models;

namespace CO453_WebApps.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        ////GET: Posts
        //public async Task<IActionResult> Index()
        //{
        //    var messages = await _context.Messages.ToListAsync();
        //    var photos = await _context.Photos.ToListAsync();

        //    List<Post> Posts = new List<Post>();

        //    Posts.AddRange(messages);
        //    Posts.AddRange(photos);
        //    return View(Posts);
        //}
        public async Task<IActionResult> Index(string sortOrder, string userName)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var posts = from p in _context.Posts
                        select p;
            if (!String.IsNullOrEmpty(userName))
            {
                posts = posts.Where(u => u.Username == userName);
            }
            switch (sortOrder)
            {
                case "name_desc":
                    posts = posts.OrderByDescending(s => s.Username);
                    break;
                case "Date":
                    posts = posts.OrderBy(s => s.Timestamp);
                    break;
                case "date_desc":
                    posts = posts.OrderByDescending(s => s.Timestamp);
                    break;
                default:
                    posts = posts.OrderBy(s => s.Username);
                    break;
            }
            return View(await posts.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.PostID == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostID,Username")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostID,Username")] Post post)
        {
            if (id != post.PostID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.PostID == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.PostID == id);
        }
    }
}

CO453-WebApps/Views/Posts/Index.cshtml
@model IEnumerable<CO453_WebApps.Models.Post>

@{
    ViewData["Title"] = "Index";
}

<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="~/css/Product%20Sans.css" />
<link rel="stylesheet" href="~/css/App04_Styles.css" />
<header>
    <img src="~/App04Images/logo.svg" style=" display: block; margin-left: auto; margin-right: auto; width: 200px;margin-top: 20px;margin-bottom:20px;">
    <hr />
    <div class="d-flex justify-content-center" style="margin-bottom:20px">
        <a class="btn" style="width:80px; border-radius:10px;background-color:#007bff;margin: 0px 5px 0px 5px;" asp-controller="PhotoPosts" asp-action="Create">
            <img src="~/img/Buttons/add_photo_alternate_white_24dp.svg">
        </a>
        <a class="btn" style="width:80px; border-radius:10px;background-color:#007bff;margin: 0px 5px 0px 5px;" asp-controller="MessagePosts" asp-action="Create">
            <img src="~/img/Buttons/post_add_white_24dp.svg">
        </a>
    </div>
    <hr />
    <div class="d-flex justify-content-center" style="margin-bottom:20px">
        <div>
            @Html.ActionLink("date_range", "Index", new { sortOrder = ViewBag.DateSortParm }, new { @class = "material-icons btn", @style = "color:white;height:37px;border-radius:10px;background-color:#245282;margin: 0px 5px 0px 5px;" })
        </div>
        <div>
            @Html.ActionLink("sort_by_alpha", "Index", new { sortOrder = ViewBag.NameSortParm }, new { @class = "material-icons btn", @style = "color:white;height:37px;border-radius:10px;background-color:#245282;margin: 0px 5px 0px 5px;" })
        </div>
        <form asp-action="Index" method="get">
            <div class="form-actions no-color d-flex justify-content-center">
                    <div>
                        <input type="text" name="userName" placeholder="Name" style="font-family:'Product Sans';border-radius:10px;border-bottom-right-radius:0px;border-top-right-radius:0px;height:37px;border-color:#cecece;margin-left:5px;border-width:1px;padding-left:5px;" />
                        <input type="submit" value="find_in_page" class="btn material-icons" style="border-radius: 10px; border-bottom-left-radius: 0px; border-top-left-radius: 0px; height: 37px; margin-top: -2px; margin-left: -5px; background-color: #245282; color: white;margin-right:5px"/>
                    </div>
                    <a class="btn material-icons" asp-action="Index" style = "color:white;height:37px;border-radius:10px;background-color:#245282;margin: 0px 5px 0px 5px;">autorenew</a>
            </div>
        </form>
    </div>

</header>
<div class="message-dashboard">
    <div class="row d-flex justify-content-around">
        @foreach (var item in Model)
        {
            MessagePost message = null;
            PhotoPost photo = null;
            if (item is MessagePost)
            {
                message = (MessagePost)item;
            }
            if (item is PhotoPost)
            {
                photo = (PhotoPost)item;
            }
            string noneIMG = "not_found.png";
            <div class="message-box">
                <div class="box-header-wrapper">
                    <p class="box-text-username">@Html.DisplayFor(modelItem => item.Username)</p>
                    <div class="d-flex justify-content-around box-wrapper-icons">
                        <a asp-controller="@(item.DiscriminatorValue)s" asp-action="Edit" asp-route-id="@item.PostID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icon-tabler-edit box-icon">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M9 7h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3"></path>
                                <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3"></path>
                                <line x1="16" y1="5" x2="19" y2="8"></line>
                            </svg>
                        </a>
                        <a asp-controller="@(item.DiscriminatorValue)s" asp-action="Details" asp-route-id="@item.PostID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icon-tabler-zoom-in box-icon">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <circle cx="10" cy="10" r="7"></circle>
                                <line x1="7" y1="10" x2="13" y2="10"></line>
                                <line x1="10" y1="7" x2="10" y2="13"></line>
                                <line x1="21" y1="21" x2="15" y2="15"></line>
                            </svg>
                        </a>
                        <a asp-controller="@(item.DiscriminatorValue)s" asp-action="Delete" asp-route-id="@item.PostID">
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icon-tabler-trash box-icon">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <line x1="4" y1="7" x2="20" y2="7"></line>
                                <line x1="10" y1="11" x2="10" y2="17"></line>
                                <line x1="14" y1="11" x2="14" y2="17"></line>
                                <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"></path>
                                <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"></path>
                            </svg>
                        </a>
                    </div>
                </div>
                @if (item.DiscriminatorValue.Equals("PhotoPost"))
                {
                    <div class="PhotoPost-img"><img class="box-img-thumbnail" src="~/App04Images/@if (photo != null) {@photo.Filename} else { @noneIMG } " onerror="this.style.display = 'none';" alt=""></div>
                    @if (photo != null)
                    {
                        <div class="box-text-wrapper d-flex">
                            <p class="text-center box-text-description align-self-center" style="width: 100%;font-size: 165%;margin-bottom: 0px;padding: 3px;padding-bottom: 0px;">@photo.Caption</p>
                        </div>
                    }
                }
                @if (item.DiscriminatorValue.Equals("MessagePost"))
                {
                    <div>
                        <img class="MessagePost-txt" src="~/img/App04/quote.svg" style="float:left;" />
                    </div>
                    @if (message != null)
                    {
                        <div class="box-text-wrapper d-flex h-100" style="height:100%">
                            <p class="text-center box-text-description align-self-center" style="width: 100%;font-size: 165%;margin-bottom: 0px;padding: 3px;padding-bottom: 0px;">@message.Message</p>
                        </div>
                    }
                    <div>
                        <img class="MessagePost-txt" src="~/img/App04/quote.svg" style="-webkit-transform: rotate(180deg); float:right;" />
                    </div>
                }
            </div>
        }
    </div>
</div>