CO453-WebApps/Controllers/HomeController.cs
using CO453_WebApps.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ConsoleAppProject.App01;
using ConsoleAppProject.App02;

namespace CO453_WebApps.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DistanceConverter(DistanceConverter converter)
        {
            return View(converter);
        }

        public IActionResult BmiCalculator(BMI model)
        {
            return View(model);
        }

        public IActionResult BmiResultM(BMI model)
        {
            ViewBag.BMIResult = model.BMIcalc(false);
            ViewBag.BMIDescription = model.BMIdescription(0);
            ViewBag.BMIColour = model.BMIdescription(1);
            return View();
        }

        public IActionResult BmiResultI(BMI model)
        {
            ViewBag.BMIResult = model.BMIcalc(true);
            ViewBag.BMIDescription = model.BMIdescription(0);
            ViewBag.BMIColour = model.BMIdescription(1);
            return View();
        }

        public IActionResult StudentMarks()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CO453-WebApps/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CO453_WebApps.Data;
using CO453_WebApps.Models;

namespace CO453_WebApps.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        ////GET: Posts
        //public async Task<IActionResult> Index()
        //{
        //    var messages = await _context.Messages.ToListAsync();
        //    var photos = await _context.Photos.ToListAsync();

        //    List<Post> Posts = new List<Post>();

        //    Posts.AddRange(messages);
        //    Posts.AddRange(photos);
        //    return View(Posts);
        //}
        public async Task<IActionResult> Index(string sortOrder, string userName)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var posts = from p in _context.Posts
                        select p;
            if (!String.IsNullOrEmpty(userName))
            {
                posts = posts.Where(u => u.Username == userName);
            }
            switch (sortOrder)
            {
                case "name_desc":
                    posts = posts.OrderByDescending(s => s.Username);
                    break;
                case "Date":
                    posts = posts.OrderBy(s => s.Timestamp);
                    break;
                case "date_desc":
                    posts = posts.OrderByDescending(s => s.Timestamp);
                    break;
                default:
                    posts = posts.OrderBy(s => s.Username);
                    break;
            }
            return View(await posts.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.PostID == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostID,Username")] Post post)
        {
            if (ModelState.IsValid)
            {
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostID,Username")] Post post)
        {
            if (id != post.PostID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.PostID == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.PostID == id);
        }
    }
}

CO453-WebApps/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CO453_WebApps.Data;
using ConsoleAppProject.App03;

namespace CO453_WebApps.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            return View(await _context.Students.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Analyse()
        {
            var students = await _context.Students.ToListAsync();
            StudentMarks stats = new StudentMarks();

            stats.Data = new string[students.Count];

            int index = 0;
            foreach (Student student in students)
            {
                stats.Data[index] = student.Name + "," + student.Marks;
                index++;
            }
            double[] gradePercentages = stats.StatFinder("multi");
            double total = gradePercentages[0];
            double a = gradePercentages[1] / total * 100;
            double b = gradePercentages[2] / total * 100;
            double c = gradePercentages[3] / total * 100;
            double d = gradePercentages[4] / total * 100;
            double f = gradePercentages[5] / total * 100;
            stats.GradeA = string.Format("{0:0.00}", a);
            stats.GradeB = string.Format("{0:0.00}", b);
            stats.GradeC = string.Format("{0:0.00}", c);
            stats.GradeD = string.Format("{0:0.00}", d);
            stats.GradeF = string.Format("{0:0.00}", f);
            stats.StatFinder("min");
            stats.StatFinder("max");
            stats.StatFinder("mean");

            return View(stats);
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Marks,Grade")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Marks,Grade")] Student student)
        {
            if (id != student.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Students.Any(e => e.ID == id);
        }
    }
}

CO453-WebApps/Views/Home/BmiCalculator.cshtml
@model ConsoleAppProject.App02.BMI;
@{
    ViewData["Title"] = "BmiCalculator";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="~/js/inputdecimal2.js"></script>
<div class="jumbotron">
    <h3 class="display-4 text-center">BMI Score Calculator</h3>
    <hr class="my-4 text-center">
    <div class="d-flex justify-content-center">
        <p class="lead" style="margin:5px;color:white">
            <a class="btn btn-primary" role="button" style="margin-top: 10px" onclick="javascript: $('#i').hide();javascript: $('#m').show();">Metric</a>
        </p>
        <p class="lead" style="margin:5px;color:white">
            <a class="btn btn-primary" role="button" style="margin-top: 10px" onclick="javascript: $('#m').hide();javascript: $('#i').show();">Imperical</a>
        </p>
    </div>
    <div id="i" style="display:none;">
        <form method="post">
            <div class="form-group">
                <h3 class="text-centre">Height</h3>
                <label for="Feet">Feet</label>
                <input type="number" class="form-control" asp-for="Feet" placeholder="Feet" required />
                <label for="Inch">Inch</label>
                <input type="number" class="form-control floatNumberField" step="0.01" asp-for="Inches" placeholder="Inches" required />
            </div>
            <div class="form-group">
                <h3 class="text-centre" style="margin-top:10px">Weight</h3>
                <label for="Pounds">Pounds</label>
                <input type="number" class="form-control floatNumberField" step="0.01" asp-for="Weight" placeholder="Pounds" required />
            </div>
            <div class="d-flex justify-content-center" style="margin-top:30px">
                <button asp-action="BMIResultI" type="submit" class="btn btn-primary btn-lg">Calculate</button>
            </div>

        </form>
    </div>
    <div id="m" style="display:block;">
        <form method="post">
            <div class="form-group">
                <h3 class="text-centre">Height</h3>
                <label for="Metres">Metres</label>
                <input type="number" class="form-control floatNumberField" step="0.01" asp-for="Height" placeholder="Metres" required />
            </div>
            <div class="form-group">
                <h3 class="text-centre" style="margin-top:10px">Weight</h3>
                <label for="Kilograms">Kilograms</label>
                <input type="number" class="form-control floatNumberField" step="0.01" asp-for="Weight" placeholder="Kilograms" required />
            </div>
            <div class="d-flex justify-content-center" style="margin-top:30px">
                <button asp-action="BMIResultM" type="submit" class="btn btn-primary btn-lg">Calculate</button>
            </div>
        </form>
    </div>
</div>

CO453-WebApps/Views/Home/BmiResultI.cshtml
@model ConsoleAppProject.App02.BMI;
@{
    ViewData["Title"] = "BmiResultI";
}

<div class="jumbotron" style="background-color:@ViewBag.BMIColour; color: white">
    <h3 class="display-4 text-center">BMI Score</h3>
    <h1 class="display-4 text-center">@ViewBag.BMIResult</h1>
    <p class="lead d-flex justify-content-center">@ViewBag.BMIDescription</p>
    <hr class="my-4 text-center">
    <p style="margin-left:10%; margin-right:10%">
        Your BMI, or Body Mass Index, is a measure of your weight compared to your height. Accurate assessments of obesity are important,
        as being overweight or obese significantly increases your risk of a variety of medical conditions including type 2 diabetes, heart disease and cancer.

        For most adults, BMI gives a good estimate of your weight-related health risks. If your BMI is over 35, your weight is definitely
        putting your health at risk, regardless of the factors below. However, there are some situations where BMI may underestimate or
        overestimate these risks in the 25-35 BMI range. The main ones are:
        <ul style="margin-left:10%; margin-right:10%">
            <li>Children</li>
            <li>Pregnant women.</li>
            <li>Muscle Builders</li>
            <li>BAME: Black, Asian and other minority ethnic groups.</li>
        </ul>
    </p>
    <p class="lead d-flex justify-content-center">
        <a class="btn btn-lg" asp-action="BmiCalculator" role="button" style="margin-top: 20px;background-color:rgba(0,0,0,0.2);outline:none;color:white">Go Back</a>
    </p>
</div>

CO453-WebApps/Views/Home/BmiResultM.cshtml
@model ConsoleAppProject.App02.BMI;
@{
    ViewData["Title"] = "BmiResultM";
}

<div class="jumbotron" style="background-color:@ViewBag.BMIColour; color: white">
    <h3 class="display-4 text-center">BMI Score</h3>
    <h1 class="display-4 text-center">@ViewBag.BMIResult</h1>
    <p class="lead d-flex justify-content-center">@ViewBag.BMIDescription</p>
    <hr class="my-4 text-center">
    <p style="margin-left:10%; margin-right:10%">
        Your BMI, or Body Mass Index, is a measure of your weight compared to your height. Accurate assessments of obesity are important,
        as being overweight or obese significantly increases your risk of a variety of medical conditions including type 2 diabetes, heart disease and cancer.

        For most adults, BMI gives a good estimate of your weight-related health risks. If your BMI is over 35, your weight is definitely
        putting your health at risk, regardless of the factors below. However, there are some situations where BMI may underestimate or
        overestimate these risks in the 25-35 BMI range. The main ones are:
        <ul style="margin-left:10%; margin-right:10%">
            <li>Children</li>
            <li>Pregnant women.</li>
            <li>Muscle Builders</li>
            <li>BAME: Black, Asian and other minority ethnic groups.</li>
        </ul>
    </p>
    <p class="lead d-flex justify-content-center">
        <a class="btn btn-lg" asp-action="BmiCalculator" role="button" style="margin-top: 20px;background-color:rgba(0,0,0,0.2);outline:none;color:white">Go Back</a>
    </p>
</div>

CO453-WebApps/Views/Home/DistanceConverter.cshtml
@model ConsoleAppProject.App01.DistanceConverter
@using ConsoleAppProject.App01

@{ ViewData["Title"] = "DistanceConverter"; }
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="~/js/inputdecimal2.js"></script>
<div class="jumbotron">
    <h3 class="display-4 text-center">Distance Converter</h3>
    <hr class="my-4 text-center">
    <div class="container">
        <div class="row" style="margin:15px">
            <div class="col-sm-6">
                <h3 class="text-center font-weight-light" style="margin-top:10px;margin-bottom:10px">Distance</h3>
                <form method="post">
                    <div class="form-group">
                        <label for="amount">Amount:</label>
                        <input type="number" class="form-control floatNumberField" step="0.01" asp-for="Unit1Value" required />
                    </div>
                    <div class="form-group">
                        <label for="converted">Convert:</label>
                        <select class="form-control" asp-for="Unit1" asp-items="Html.GetEnumSelectList<DistanceUnits>()" required>
                            <option value="">none</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="toConvert">To:</label>
                        <select class="form-control" asp-for="Unit2" asp-items="Html.GetEnumSelectList<DistanceUnits>()" required>
                            <option value="">none</option>
                        </select>
                    </div>
                    <div class="d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary btn-lg" style="margin-bottom:15px">Convert</button>
                    </div>
                </form>
            </div>
            <div class="col-sm-6" style="background-color:rgba(255,255,255,0.8); border-radius:5px;min-height:275px">
                <h3 class="text-center font-weight-light" style="margin-top:10px;">Result</h3>

                <textarea class="text-center font-weight-bolder h3" placeholder="Enter required values to see results" style="width:100%;min-height:300px;outline:none;border:none;margin-bottom:10px;border-radius:5px;padding:15px;color:#3d3d3d">@Model.ConverterResult(true)</textarea>
            </div>
        </div>
    </div>
</div>

CO453-WebApps/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "H.S. Home Page";
}
<div class="jumbotron">
    <h1 class="display-4 text-center">CO453 Programming</h1>
    <hr class="my-4 text-center">
    <h2 class="text-center">By Haroon Sadiq</h2>
</div>
<div class="row">
    <div class="col-sm-4" style="margin-top:10px;height:auto;">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">App01: Distance Converter</h5>
                <p class="card-text">A web app which converts multiple units and outputs a result.</p>
                <a asp-action="DistanceConverter" class="btn btn-primary">App01</a>
            </div>
        </div>
    </div>
    <div class="col-sm-4" style="margin-top:10px;height:auto;">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">App02: BMI Calculator</h5>
                <p class="card-text">A web app which calculates your BMI and outputs with a description.</p>
                <a asp-action="BmiCalculator" class="btn btn-primary">App02</a>
            </div>
        </div>
    </div>
    <div class="col-sm-4" style="margin-top:10px;height:auto;">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">App03: Student Marks</h5>
                <p class="card-text">A web app using a SQL database to store, modify, delete and view student marks</p>
                <a asp-controller="Students" asp-action="Index" class="btn btn-primary">App03</a>
            </div>
        </div>
    </div>
    <div class="col-sm-4" style="margin-top:10px;height:auto;">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">App04: Social Media</h5>
                <p class="card-text">A web app using a SQL database to store, modify, delete and view social media</p>
                <a asp-controller="Posts" asp-action="Index" class="btn btn-primary">App04</a>
            </div>
        </div>
    </div>
</div>